version: '3.9'

services:
  postgres-iam:
    image: postgres:16-alpine
    container_name: orion-iam-db
    environment:
      POSTGRES_DB: orion_iam
      POSTGRES_USER: orion
      POSTGRES_PASSWORD: orion_pass
    ports:
      - "5432:5432"
    volumes:
      - orion_iam_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orion -d orion_iam"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  orion_iam_data:
